import type {
  CharacterAnimation,
  CharacterAppearance,
  CharacterFacing,
} from "../../../components/editor/hero/characterTypes";

export type GlobalNpcCatalogEntry = {
  id: string;
  name: string;
  appearance: CharacterAppearance;
  lines: string[];
  walking?: boolean;
  animation?: CharacterAnimation;
  facing?: CharacterFacing;
  sheetAssetId?: string;
  tags?: string[];
};

export const NPC_CATALOG = [
  {
    id: "npc-satiria-garden-guide",
    name: "Satiria Garden Guide",
    appearance: {
      body: "body_48x48_01",
      eyes: "eyes_48x48_01",
      hair: "hairstyle_01_48x48_01",
      outfit: "outfit_01_48x48_01",
      accessory: "none",
      skinColor: "default",
      hairColor: "brown",
      outfitColor: "green",
    },
    lines: ["Keep the paths tidy and the tall grass lively."],
    walking: true,
    facing: "down",
    tags: ["satiria", "guide"],
  },
  {
    id: "npc-satiria-market-auntie",
    name: "Satiria Market Auntie",
    appearance: {
      body: "body_48x48_02",
      eyes: "eyes_48x48_02",
      hair: "hairstyle_03_48x48_01",
      outfit: "outfit_02_48x48_01",
      accessory: "none",
      skinColor: "warm",
      hairColor: "black",
      outfitColor: "red",
    },
    lines: ["Fresh bread, fresh gossip, both warm by sunrise."],
    walking: true,
    facing: "left",
    tags: ["satiria", "market"],
  },
  {
    id: "npc-brexiton-bowler",
    name: "Brexiton Bowler",
    appearance: {
      body: "body_48x48_03",
      eyes: "eyes_48x48_03",
      hair: "hairstyle_02_48x48_01",
      outfit: "outfit_03_48x48_01",
      accessory: "accessory_25_black_cylinder_48x48",
      skinColor: "pale",
      hairColor: "brown",
      outfitColor: "black",
    },
    lines: ["The gate is open, closed, amended, then open again."],
    walking: true,
    facing: "down",
    tags: ["brexiton", "formal"],
  },
  {
    id: "npc-cryptonia-bro",
    name: "Cryptonia Bro",
    appearance: {
      body: "body_48x48_04",
      eyes: "eyes_48x48_04",
      hair: "hairstyle_04_48x48_01",
      outfit: "outfit_01_48x48_02",
      accessory: "accessory_15_glasses_48x48_01",
      skinColor: "tan",
      hairColor: "blonde",
      outfitColor: "yellow",
    },
    lines: ["This coin is definitely about to recover."],
    walking: true,
    facing: "right",
    tags: ["cryptonia", "crypto"],
  },
  {
    id: "npc-factcheck-scholar",
    name: "Factcheck Scholar",
    appearance: {
      body: "body_48x48_05",
      eyes: "eyes_48x48_05",
      hair: "hairstyle_03_48x48_02",
      outfit: "outfit_04_48x48_01",
      accessory: "accessory_16_monocle_48x48_01",
      skinColor: "brown",
      hairColor: "black",
      outfitColor: "blue",
    },
    lines: ["That depends on which footnote you trust."],
    walking: false,
    facing: "down",
    tags: ["factcheck", "scholar"],
  },
  {
    id: "npc-inflatopolis-tango",
    name: "Inflatopolis Tango",
    appearance: {
      body: "body_48x48_06",
      eyes: "eyes_48x48_06",
      hair: "hairstyle_01_48x48_02",
      outfit: "outfit_05_48x48_01",
      accessory: "none",
      skinColor: "tan",
      hairColor: "black",
      outfitColor: "red",
    },
    lines: ["Yesterday the empanada cost half as much."],
    walking: true,
    facing: "up",
    tags: ["inflatopolis", "tango"],
  },
  {
    id: "npc-promptford-oracle",
    name: "Promptford Oracle",
    appearance: {
      body: "body_48x48_07",
      eyes: "eyes_48x48_07",
      hair: "hairstyle_02_48x48_02",
      outfit: "outfit_02_48x48_02",
      accessory: "none",
      skinColor: "default",
      hairColor: "blue",
      outfitColor: "purple",
    },
    lines: ["I asked three assistants and they all suggested a cafe."],
    walking: true,
    facing: "left",
    tags: ["promptford", "oracle"],
  },
  {
    id: "npc-ragebait-filmmaker",
    name: "Ragebait Filmmaker",
    appearance: {
      body: "body_48x48_08",
      eyes: "eyes_48x48_01",
      hair: "hairstyle_04_48x48_02",
      outfit: "outfit_03_48x48_02",
      accessory: "accessory_04_snapback_48x48_01",
      skinColor: "warm",
      hairColor: "red",
      outfitColor: "blue",
    },
    lines: ["Can you say that again, but more dramatically?"],
    walking: true,
    facing: "right",
    tags: ["ragebait", "media"],
  },
  {
    id: "npc-surveillia-robot-tech",
    name: "Surveillia Robot Tech",
    appearance: {
      body: "body_48x48_09",
      eyes: "eyes_48x48_02",
      hair: "none",
      outfit: "outfit_04_48x48_02",
      accessory: "accessory_20_worker_helmet_48x48",
      skinColor: "pale",
      hairColor: "white",
      outfitColor: "white",
    },
    lines: ["The cameras only blink when they are pretending not to watch."],
    walking: true,
    facing: "down",
    tags: ["surveillia", "robotics"],
  },
  {
    id: "npc-wokeshire-tourist",
    name: "Wokeshire Tourist",
    appearance: {
      body: "body_48x48_01",
      eyes: "eyes_48x48_03",
      hair: "hairstyle_01_48x48_03",
      outfit: "outfit_05_48x48_02",
      accessory: "accessory_03_backpack_48x48_01",
      skinColor: "default",
      hairColor: "purple",
      outfitColor: "green",
    },
    lines: ["I am just here for the canal photos and complicated menus."],
    walking: true,
    facing: "down",
    tags: ["wokeshire", "tourist"],
  },
] as const satisfies readonly GlobalNpcCatalogEntry[];
