import type { LimeZuAssetMetadata } from "./AssetCatalog";

/**
 * Global LimeZu asset metadata.
 * Generated by the Satiria Asset Manager.
 */
export const LIMEZU_ASSET_METADATA = {
  "asset_tileset3_mv_00_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_06": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_07": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_08": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_11": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_13": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_14": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_00_15": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_06": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_07": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_08": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_11": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_13": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_14": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_01_15": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_06": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_07": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_08": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_11": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_13": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_14": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_02_15": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_06": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_07": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_08": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_11": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_13": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_03_14": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_06": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_07": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_08": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_11": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_13": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_04_14": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_06": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_07": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_08": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_11": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_13": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_05_14": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_06": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_07": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_08": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_11": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_13": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_14": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_06_15": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_06": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_07": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_08": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_11": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_13": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_14": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_07_15": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_07": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_08": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_11": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_13": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_14": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_08_15": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_06": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_07": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_08": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_11": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_13": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_14": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_09_15": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_11": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_13": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_14": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_10_15": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_11_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_11_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_11_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_11_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_11_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_11_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_11_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_11_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_11_11": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_11_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_12_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_12_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_12_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_12_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_12_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_12_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_12_09": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_12_10": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_12_12": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_13_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_13_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_13_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_13_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_13_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_13_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_14_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_14_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_14_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_14_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_14_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_14_05": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_15_00": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_15_01": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_15_02": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_15_03": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_15_04": {
    "buildingPlacement": "outside"
  },
  "asset_tileset3_mv_15_05": {
    "buildingPlacement": "outside"
  }
} as const satisfies LimeZuAssetMetadata;
