import type { LimeZuAssetMetadata } from "./AssetCatalog";

/**
 * Global LimeZu asset metadata.
 * Generated by the Satiria Asset Manager.
 */
export const LIMEZU_ASSET_METADATA = {} as const satisfies LimeZuAssetMetadata;
