const BUILDING_TILES = new Set(["B", "H", "P", "A", "U", "I"]);

export const tileShapeClassFor = (rows: string[][], x: number, y: number, tile: string) => {
  if (!BUILDING_TILES.has(tile)) return "";
  const same = (dx: number, dy: number) => rows[y + dy]?.[x + dx] === tile;
  return [
    "building-tile",
    same(0, -1) ? "building-mid-y" : "building-top",
    same(0, 1) ? "building-mid-y" : "building-bottom",
    same(-1, 0) ? "building-mid-x" : "building-left",
    same(1, 0) ? "building-mid-x" : "building-right",
  ].join(" ");
};

export const objectClassFor = (obj: string) => {
  const map: Record<string, string> = {
    SATIRIA_SHOP: "world-object satiria-building satiria-shop",
    SATIRIA_HEALING: "world-object satiria-building satiria-healing",
    SATIRIA_HOUSE_BLUE: "world-object satiria-building satiria-house-blue",
    SATIRIA_HOUSE_RED: "world-object satiria-building satiria-house-red",
    SATIRIA_INN: "world-object satiria-building satiria-inn",
    SATIRIA_STATION: "world-object satiria-building satiria-station",
    SATIRIA_FOUNTAIN: "world-object satiria-fountain",
    SATIRIA_STATUE: "world-object satiria-statue",
    SATIRIA_LAMP: "world-object satiria-lamp",
    SATIRIA_BENCH: "world-object satiria-bench",
    SATIRIA_POND_SIGN: "world-object satiria-pond-sign",
    SHOP: "world-object object-shop",
    HEAL: "world-object object-heal",
    HOME: "world-object object-home",
    "⌂": "world-object object-house",
    DOOR_SHOP: "world-object object-door-shop",
    DOOR_HEAL: "world-object object-door-heal",
    DOOR_HOME: "world-object object-door-home",
    "★": "world-object object-save",
    SIGN: "world-object object-sign",
    CAVE: "world-object object-cave",
    EXIT: "world-object object-exit",
    POTN: "world-object object-potion",
    BALL: "world-object object-ball",
    BED: "world-object object-bed",
    TV: "world-object object-tv",
    "←": "world-object object-arrow-left",
    "→": "world-object object-arrow-right",
    TRAIN: "world-object object-train-station",
    ARROW_N: "world-object object-route object-route-n",
    ARROW_S: "world-object object-route object-route-s",
    ARROW_E: "world-object object-route object-route-e",
    ARROW_W: "world-object object-route object-route-w",
    ARROW_NE: "world-object object-route object-route-ne",
    ARROW_NW: "world-object object-route object-route-nw",
    ARROW_SE: "world-object object-route object-route-se",
    ARROW_SW: "world-object object-route object-route-sw",
    LONDON_CLOCK: "world-object object-london-clock",
    PARLIAMENT: "world-object object-parliament",
    PHONE_BOX: "world-object object-phone-box",
    BLACK_CAB: "world-object object-black-cab",
    DOUBLE_DECKER: "world-object object-double-decker",
    LAMP_POST: "world-object object-lamp-post",
    VOTE_GATE: "world-object object-vote-gate",
    EIFFEL_TOWER: "world-object object-eiffel-tower",
    PARIS_CAFE: "world-object object-paris-cafe",
    BAGUETTE_STAND: "world-object object-baguette-stand",
    METRO_SIGN: "world-object object-metro-sign",
    SEINE_BRIDGE: "world-object object-seine-bridge",
    AI_ORACLE: "world-object object-ai-oracle",
    CANAL_BRIDGE: "world-object object-canal-bridge",
    BICYCLE: "world-object object-bicycle",
    TULIP_STAND: "world-object object-tulip-stand",
    WINDMILL: "world-object object-windmill",
    CANAL_HOUSE: "world-object object-canal-house",
    BURJ_TOWER: "world-object object-burj-tower",
    PALM_ISLAND: "world-object object-palm-island",
    LUXURY_CAR: "world-object object-luxury-car",
    CRYPTO_BILLBOARD: "world-object object-crypto-billboard",
    YACHT: "world-object object-yacht",
    GOLD_ATM: "world-object object-gold-atm",
    PEARL_TOWER: "world-object object-pearl-tower",
    SHANGHAI_TOWER: "world-object object-shanghai-tower",
    NEON_SIGN: "world-object object-neon-sign",
    CAMERA_POLE: "world-object object-camera-pole",
    RIVER_FERRY: "world-object object-river-ferry",
    DATA_KIOSK: "world-object object-data-kiosk",
    MOSCOW_CATHEDRAL: "world-object object-moscow-cathedral",
    KREMLIN_WALL: "world-object object-kremlin-wall",
    SNOW_STATUE: "world-object object-snow-statue",
    RUMOR_KIOSK: "world-object object-rumor-kiosk",
    RED_STAR: "world-object object-red-star",
    OBELISCO: "world-object object-obelisco",
    TANGO_STAGE: "world-object object-tango-stage",
    STEAK_GRILL: "world-object object-steak-grill",
    PESO_SIGN: "world-object object-peso-sign",
    PRICE_BOARD: "world-object object-price-board",
    BALCONY_HOUSE: "world-object object-balcony-house",
    CHRIST_STATUE: "world-object object-christ-statue",
    SUGARLOAF: "world-object object-sugarloaf",
    BEACH_UMBRELLA: "world-object object-beach-umbrella",
    CARNIVAL_DRUMS: "world-object object-carnival-drums",
    RIO_BOAT: "world-object object-rio-boat",
    CABLE_CAR: "world-object object-cable-car",
    GOLDEN_GATE: "world-object object-golden-gate",
    TRAM_CAR: "world-object object-tram-car",
    TECH_BILLBOARD: "world-object object-tech-billboard",
    HILL_HOUSE: "world-object object-hill-house",
    FOG_HORN: "world-object object-fog-horn",
    INDIA_GATE: "world-object object-india-gate",
    TUKTUK: "world-object object-tuktuk",
    LOTUS_DOME: "world-object object-lotus-dome",
    FACT_FOUNTAIN: "world-object object-fact-fountain",
    MARKET_STALL: "world-object object-market-stall",
    NEWS_STAND: "world-object object-news-stand",
    CLERK: "clerk-sprite",
    NURSE: "nurse-sprite",
  };
  return map[obj] ?? "world-object object-sign";
};

